config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  
  get 'profile' => 'users#edit'
  put 'updateUser' => 'users#update'
  get 'login' => 'users#login'
  put 'verify' => 'users#verify'
  put 'signup' => 'users#create'
  
  get 'mybanquets' => 'banquets#show'
  get 'findbanquets' => 'banquets#find'
  get 'newbanquet' => 'banquets#new'
  put 'createbanquet' => 'banquets#create'
  
  get 'transactions' => 'transactions#show'
  get 'rsvp/:id' => 'transactions#create', as: :rsvp
end

app/models/aggregate.rb
class Aggregate < ActiveRecord::Base
    has_many :events
end

app/models/banquet.rb
class Banquet < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
    belongs_to :aggregate
    attr_reader :aggType, :aggStatus
    attr_writer :aggType, :aggStatus
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
    attr_reader :banquet_name, :customer_email, :recipient_email
    attr_writer :banquet_name, :customer_email, :recipient_email
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banquets_controller.rb
class BanquetsController < ApplicationController

  def find
    if(session[:user_id])
      user = User.find(session[:user_id])
      zip = user.zip_code
      @banquets = Banquet.where(:zip_code => zip)
    else
      redirect_to login_path
    end
  end

  def show
    if(session[:user_id])
      @banquets = Banquet.where(:hostID => session[:user_id])
    else
      redirect_to login_path
    end
  end

  def create
    if(session[:user_id])
      Banquet.create!(:hostID => session[:user_id], :banquet_name => params[:banquet][:name], :zip_code => params[:banquet][:zip_code], :start => params[:banquet][:start], :end => params[:banquet][:end], :entryPrice => params[:banquet][:entryPrice], :entryLimit => params[:banquet][:entryLimit])
      redirect_to mybanquets_path
    else
      redirect_to login_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @events.each do |event|
      agg = Aggregate.find(event[:aggregate_id])
      event.aggType = agg[:aggType]
      event.aggStatus = agg[:aggStatus]
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def show
    if(session[:user_id])
      user_id = session[:user_id]
      
      @debits = Transaction.where(:fromID => user_id)
      @debits.each do |debit|
        debit.banquet_name = Banquet.find(debit.banquetID).banquet_name
        debit.customer_email = User.find(user_id).email
        debit.recipient_email = User.find(debit.toID).email
      end
      
      @credits = Transaction.where(:toID => user_id)
      @credits.each do |credit|
        credit.banquet_name = Banquet.find(credit.banquetID).banquet_name
        credit.customer_email = User.find(credit.toID).email
        credit.recipient_email = User.find(user_id).email
      end
    else
      redirect_to login_path
    end
  end

  def create
    if(session[:user_id])
      banquet = Banquet.find(params[:id])
      Transaction.create!(:fromID => session[:user_id], :toID => banquet[:hostID], :banquetID => banquet[:id], :amount => banquet[:entryPrice])
      redirect_to transactions_path
    else
      redirect_to login_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def user_params
    params.require(:user).permit(:first_name, :middle_name, :last_name, :zip_code)
  end
  
  def login
    temp = flash[:notice]
    reset_session
    flash[:notice] = temp
  end
  
  def verify
    users = User.where(email: params[:user][:login_email])
    if(users.length < 1)
      flash[:notice] = "Invalid email or password"
      redirect_to login_path
    elsif(users.length == 1)
      if(users[0][:password] == params[:user][:login_password])
        session[:user_id] = users[0][:id]
        redirect_to profile_path
      else
        flash[:notice] = "Invalid email or password"
        redirect_to login_path
      end
    else
      flash[:notice] = "Multiple users with that email. How is that even possible?"
      redirect_to login_path
    end
  end
  
  def create
    if(User.find_by(email: params[:user][:signup_email]))
      flash[:notice] = "A profile already exists with that email address"
      redirect_to login_path
    else
      @user = User.create!(:email => params[:user][:signup_email], :password => params[:user][:signup_password])
      session[:user_id] = @user[:id]
      flash[:notice] = "The new user's id is '#{session[:user_id]}'"
      redirect_to profile_path
    end
  end

  def edit
    if(session[:user_id])
      @user = User.find(session[:user_id])
    else
      redirect_to login_path
    end
  end

  def update
    if(session[:user_id])
      @user = User.find(session[:user_id])
      @user.update_attributes!(user_params)
      session[:user] = @user
      flash[:notice] = "Profile info was successfully updated."
      redirect_to '/profile'
    else
      redirect_to login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/banquets/find.html.haml
-#  This file is app/views/events/find.html.haml
%h1 Find Banquets

%table#banquets
  %thead
    %tr
      %th Banquet Name
      %th Start
      %th End
      %th Entry Price
      %th RSVP
  %tbody
    - @banquets.each do |banquet|
      %tr
        %td= banquet.banquet_name
        %td= banquet.start
        %td= banquet.end
        %td= banquet.entryPrice
        %td= link_to "RSVP to #{banquet.banquet_name}", rsvp_path(banquet)

app/views/banquets/new.html.haml
-#  This file is app/views/events/new.html.haml
%h1 New Banquet

= form_tag('/createbanquet', method: :put) do

  = label :banquet, :name, 'Banquet Name'
  = text_field :banquet, 'name'
  
  = label :banquet, :zip_code, 'Zip Code'
  = text_field :banquet, 'zip_code'
  
  = label :banquet, :start, 'Starting Date/Time'
  = text_field :banquet, 'start'
  
  = label :banquet, :end, 'Ending Date/Time'
  = text_field :banquet, 'end'
  
  = label :banquet, :entryPrice, 'Entry Price'
  = text_field :banquet, 'entryPrice'
  
  = label :banquet, :entryLimit, 'Entry Limit'
  = text_field :banquet, 'entryLimit'

  = submit_tag 'Submit'

app/views/banquets/show.html.haml
-#  This file is app/views/events/show.html.haml
%h1 My Banquets

%table#banquets
  %thead
    %tr
      %th Banquet Name
      %th Zip Code
      %th Start
      %th End
      %th Entry Price
      %th Entry Limit
  %tbody
    - @banquets.each do |banquet|
      %tr
        %td= banquet.banquet_name
        %td= banquet.zip_code
        %td= banquet.start
        %td= banquet.end
        %td= banquet.entryPrice
        %td= banquet.entryLimit

app/views/events/index.html.haml
-#  This file is app/views/events/index.html.haml
%h1 All Events

%table#events
  %thead
    %tr
      %th Aggregate ID
      %th Aggregate Type
      %th Aggregate Status
      %th Event ID
      %th Event Type
      %th Event Data
  %tbody
    - @events.each do |full_event|
      %tr
        %td= full_event.aggregate_id
        %td= full_event.aggType
        %td= full_event.aggStatus
        %td= full_event.id
        %td= full_event.eventType
        %td= full_event.eventData

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Banquet
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
  
    %h1.title Banquet
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
    %table#panels{:style => "width:100%"}
      %thead
        %tr
          %th 
            %table#panels
              %tbody
                %tr 
                  %td= link_to "Profile", profile_path
                %tr 
                  %td= link_to "My Banquets", mybanquets_path
                %tr 
                  %td= link_to "New Banquet", newbanquet_path
                %tr 
                  %td= link_to "Find Banquets", findbanquets_path
                %tr 
                  %td= link_to "Transaction History", transactions_path
                %tr 
                  %td= link_to "Logout", login_path
          %th
            #main
              = yield

app/views/transactions/show.html.haml
-#  This file is app/views/events/show.html.haml
%h1 Debits

%table#transactions
  %thead
    %tr
      %th Recipient Email
      %th Banquet Name
      %th Amount
  %tbody
    - @debits.each do |debit|
      %tr
        %td= debit.recipient_email
        %td= debit.banquet_name
        %td= debit.amount

%h1 Credits

%table#transactions
  %thead
    %tr
      %th Customer Username
      %th Banquet Name
      %th Amount
  %tbody
    - @credits.each do |credit|
      %tr
        %td= credit.customer_email
        %td= credit.banquet_name
        %td= credit.amount

app/views/users/edit.html.haml
-# in app/views/users/edit.html.haml

%h2 Details about #{@user.first_name} #{@user.middle_name} #{@user.last_name} 

= form_tag('/updateUser', method: :put) do

  = label :user, :first_name, 'First Name'
  = text_field :user, 'first_name'

  = label :user, :middle_name, 'Middle Name'
  = text_field :user, 'middle_name'

  = label :user, :last_name, 'Last Name'
  = text_field :user, 'last_name'

  = label :user, :zip_code, 'Zip Code'
  = number_field :user, 'zip_code'

  = submit_tag 'Update Profile Info'

app/views/users/login.html.haml
-# in app/views/users/login.html.haml

%h2 Login

= form_tag('/verify', method: :put) do

  = label :user, :login_email, 'Email'
  = text_field :user, 'login_email'

  = label :user, :login_password, 'Password'
  = text_field :user, 'login_password'

  = submit_tag 'Login'


%h2 Sign Up

= form_tag('/signup', method: :put) do

  = label :user, :signup_email, 'Email'
  = text_field :user, 'signup_email'

  = label :user, :signup_password, 'Password'
  = text_field :user, 'signup_password'

  = submit_tag 'Sign Up'